const RAW_PARTS = [
  { part: "A", questions: [
    {number:1,word:"ABSTAIN",options:{A:"Participate",B:"Refrain",C:"Continue",D:"Demand"},answer:"B",explanation:"Abstain means to avoid or refrain from something."},
    {number:2,word:"ACCORD",options:{A:"Disagreement",B:"Agreement",C:"Refusal",D:"Conflict"},answer:"B",explanation:"Accord means agreement or harmony."},
    {number:3,word:"ADAMANT",options:{A:"Flexible",B:"Unyielding",C:"Weak",D:"Gentle"},answer:"B",explanation:"Adamant means refusing to change one's mind."},
    {number:4,word:"ADEPT",options:{A:"Clumsy",B:"Skilled",C:"Weak",D:"Ignorant"},answer:"B",explanation:"Adept means highly skilled."},
    {number:5,word:"ADMONISH",options:{A:"Praise",B:"Warn",C:"Encourage",D:"Reward"},answer:"B",explanation:"Admonish means to caution or scold gently."},
    {number:6,word:"AFFLUENT",options:{A:"Poor",B:"Wealthy",C:"Honest",D:"Weak"},answer:"B",explanation:"Affluent means rich or prosperous."},
    {number:7,word:"AGGRAVATE",options:{A:"Improve",B:"Worsen",C:"Heal",D:"Reduce"},answer:"B",explanation:"Aggravate means to make worse."},
    {number:8,word:"ALLEGE",options:{A:"Confirm",B:"Claim",C:"Deny",D:"Reject"},answer:"B",explanation:"Allege means to assert without proof."},
    {number:9,word:"AMIABLE",options:{A:"Hostile",B:"Friendly",C:"Angry",D:"Rude"},answer:"B",explanation:"Amiable means pleasant and friendly."},
    {number:10,word:"ANOMALY",options:{A:"Normality",B:"Irregularity",C:"Balance",D:"Similarity"},answer:"B",explanation:"Anomaly means deviation from the norm."},
    {number:11,word:"ANTIPATHY",options:{A:"Affection",B:"Hatred",C:"Sympathy",D:"Friendship"},answer:"B",explanation:"Antipathy means strong dislike."},
    {number:12,word:"APPRISE",options:{A:"Inform",B:"Hide",C:"Delay",D:"Ignore"},answer:"A",explanation:"Apprise means to notify or inform."},
    {number:13,word:"ASSIDUOUS",options:{A:"Lazy",B:"Hardworking",C:"Weak",D:"Careless"},answer:"B",explanation:"Assiduous means diligent and persistent."},
    {number:14,word:"AVARICE",options:{A:"Generosity",B:"Greed",C:"Honesty",D:"Patience"},answer:"B",explanation:"Avarice means extreme greed."},
    {number:15,word:"BENIGN",options:{A:"Harmful",B:"Gentle",C:"Cruel",D:"Violent"},answer:"B",explanation:"Benign means kind and harmless."},
    {number:16,word:"BREVITY",options:{A:"Lengthiness",B:"Conciseness",C:"Weakness",D:"Silence"},answer:"B",explanation:"Brevity means shortness in speech or writing."},
    {number:17,word:"CANDIDATE",options:{A:"Applicant",B:"Judge",C:"Teacher",D:"Officer"},answer:"A",explanation:"Candidate means a person applying for a position."},
    {number:18,word:"COERCE",options:{A:"Persuade gently",B:"Force",C:"Encourage",D:"Support"},answer:"B",explanation:"Coerce means to compel by force."},
    {number:19,word:"COLOSSAL",options:{A:"Tiny",B:"Huge",C:"Weak",D:"Narrow"},answer:"B",explanation:"Colossal means extremely large."},
    {number:20,word:"COMPASSION",options:{A:"Cruelty",B:"Sympathy",C:"Anger",D:"Hatred"},answer:"B",explanation:"Compassion means pity and concern for others."},
    {number:21,word:"CONCISE",options:{A:"Wordy",B:"Brief",C:"Confusing",D:"Lengthy"},answer:"B",explanation:"Concise means expressing much in few words."},
    {number:22,word:"CONDONE",options:{A:"Punish",B:"Forgive",C:"Reject",D:"Refuse"},answer:"B",explanation:"Condone means to overlook or forgive wrongdoing."},
    {number:23,word:"CONSPICUOUS",options:{A:"Hidden",B:"Noticeable",C:"Tiny",D:"Secretive"},answer:"B",explanation:"Conspicuous means clearly visible."},
    {number:24,word:"CREDIBLE",options:{A:"Doubtful",B:"Believable",C:"Weak",D:"False"},answer:"B",explanation:"Credible means trustworthy."},
    {number:25,word:"CURTAIL",options:{A:"Extend",B:"Reduce",C:"Expand",D:"Increase"},answer:"B",explanation:"Curtail means to cut short."},
    {number:26,word:"DEBILITATE",options:{A:"Strengthen",B:"Weaken",C:"Encourage",D:"Improve"},answer:"B",explanation:"Debilitate means to make weak."},
    {number:27,word:"DECORUM",options:{A:"Rudeness",B:"Proper behavior",C:"Violence",D:"Disorder"},answer:"B",explanation:"Decorum means dignified behavior."},
    {number:28,word:"DEFAMATION",options:{A:"Praise",B:"Slander",C:"Respect",D:"Support"},answer:"B",explanation:"Defamation means damaging reputation falsely."},
    {number:29,word:"DELIBERATE",options:{A:"Careless",B:"Intentional",C:"Sudden",D:"Weak"},answer:"B",explanation:"Deliberate means done intentionally."},
    {number:30,word:"DESPAIR",options:{A:"Hope",B:"Hopelessness",C:"Joy",D:"Excitement"},answer:"B",explanation:"Despair means complete loss of hope."},
    {number:31,word:"DETER",options:{A:"Encourage",B:"Discourage",C:"Support",D:"Help"},answer:"B",explanation:"Deter means prevent from acting."},
    {number:32,word:"DEXTERITY",options:{A:"Clumsiness",B:"Skill",C:"Weakness",D:"Laziness"},answer:"B",explanation:"Dexterity means skillfulness."},
    {number:33,word:"DIGRESS",options:{A:"Continue directly",B:"Deviate",C:"Finish",D:"Clarify"},answer:"B",explanation:"Digress means stray from the topic."},
    {number:34,word:"DISCREET",options:{A:"Careful",B:"Loud",C:"Open",D:"Foolish"},answer:"A",explanation:"Discreet means tactful and cautious."},
    {number:35,word:"DISMAL",options:{A:"Cheerful",B:"Miserable",C:"Pleasant",D:"Bright"},answer:"B",explanation:"Dismal means gloomy."},
    {number:36,word:"DIVERGE",options:{A:"Unite",B:"Differ",C:"Agree",D:"Join"},answer:"B",explanation:"Diverge means move apart."},
    {number:37,word:"ELUCIDATE",options:{A:"Confuse",B:"Explain",C:"Hide",D:"Ignore"},answer:"B",explanation:"Elucidate means clarify."},
    {number:38,word:"EMPATHY",options:{A:"Indifference",B:"Understanding",C:"Cruelty",D:"Hatred"},answer:"B",explanation:"Empathy means understanding others' feelings."},
    {number:39,word:"ENIGMA",options:{A:"Answer",B:"Mystery",C:"Truth",D:"Clarity"},answer:"B",explanation:"Enigma means something mysterious."},
    {number:40,word:"ENTICE",options:{A:"Repel",B:"Attract",C:"Reject",D:"Refuse"},answer:"B",explanation:"Entice means lure or attract."},
    {number:41,word:"ERODE",options:{A:"Build",B:"Wear away",C:"Strengthen",D:"Improve"},answer:"B",explanation:"Erode means gradually destroy."},
    {number:42,word:"EXPLICIT",options:{A:"Vague",B:"Clear",C:"Hidden",D:"Confusing"},answer:"B",explanation:"Explicit means clearly expressed."},
    {number:43,word:"EXTOL",options:{A:"Criticize",B:"Praise",C:"Reject",D:"Ignore"},answer:"B",explanation:"Extol means praise enthusiastically."},
    {number:44,word:"FALTER",options:{A:"Continue strongly",B:"Hesitate",C:"Improve",D:"Support"},answer:"B",explanation:"Falter means lose confidence briefly."},
    {number:45,word:"FICKLE",options:{A:"Loyal",B:"Unstable",C:"Reliable",D:"Honest"},answer:"B",explanation:"Fickle means changing frequently."},
    {number:46,word:"FORBEAR",options:{A:"Continue",B:"Refrain",C:"Encourage",D:"Approve"},answer:"B",explanation:"Forbear means hold back."},
    {number:47,word:"FRANTIC",options:{A:"Calm",B:"Wild",C:"Relaxed",D:"Peaceful"},answer:"B",explanation:"Frantic means uncontrolled with fear or worry."},
    {number:48,word:"HINDER",options:{A:"Assist",B:"Obstruct",C:"Encourage",D:"Support"},answer:"B",explanation:"Hinder means create difficulties."},
    {number:49,word:"IMMINENT",options:{A:"Distant",B:"Near",C:"Delayed",D:"Hidden"},answer:"B",explanation:"Imminent means about to happen."},
    {number:50,word:"IMPARTIAL",options:{A:"Biased",B:"Fair",C:"Partial",D:"Emotional"},answer:"B",explanation:"Impartial means unbiased."},
    {number:51,word:"IMPERATIVE",options:{A:"Optional",B:"Necessary",C:"Weak",D:"Minor"},answer:"B",explanation:"Imperative means absolutely necessary."},
    {number:52,word:"IMPLICIT",options:{A:"Direct",B:"Implied",C:"Open",D:"Clear"},answer:"B",explanation:"Implicit means understood though not stated."},
    {number:53,word:"INCESSANT",options:{A:"Occasional",B:"Continuous",C:"Rare",D:"Quiet"},answer:"B",explanation:"Incessant means nonstop."},
    {number:54,word:"INCITE",options:{A:"Calm",B:"Provoke",C:"Delay",D:"Prevent"},answer:"B",explanation:"Incite means encourage violent action."},
    {number:55,word:"INDIGENT",options:{A:"Wealthy",B:"Poor",C:"Noble",D:"Rich"},answer:"B",explanation:"Indigent means poor and needy."},
    {number:56,word:"INEVITABLE",options:{A:"Avoidable",B:"Unavoidable",C:"Doubtful",D:"Optional"},answer:"B",explanation:"Inevitable means certain to happen."},
    {number:57,word:"INFAMOUS",options:{A:"Famous for good",B:"Notorious",C:"Respectable",D:"Noble"},answer:"B",explanation:"Infamous means famous for bad reasons."},
    {number:58,word:"INGENIOUS",options:{A:"Dull",B:"Clever",C:"Weak",D:"Ordinary"},answer:"B",explanation:"Ingenious means inventive and clever."},
    {number:59,word:"INTEGRITY",options:{A:"Dishonesty",B:"Honesty",C:"Weakness",D:"Fear"},answer:"B",explanation:"Integrity means moral honesty."},
    {number:60,word:"INTREPID",options:{A:"Fearful",B:"Brave",C:"Weak",D:"Nervous"},answer:"B",explanation:"Intrepid means fearlessness."},
    {number:61,word:"JUDICIOUS",options:{A:"Foolish",B:"Wise",C:"Careless",D:"Reckless"},answer:"B",explanation:"Judicious means showing good judgment."},
    {number:62,word:"JUVENILE",options:{A:"Mature",B:"Childish",C:"Serious",D:"Adult"},answer:"B",explanation:"Juvenile means youthful or immature."},
    {number:63,word:"LINGER",options:{A:"Hurry",B:"Delay",C:"Rush",D:"Finish"},answer:"B",explanation:"Linger means stay longer than necessary."},
    {number:64,word:"MALIGN",options:{A:"Praise",B:"Defame",C:"Respect",D:"Honor"},answer:"B",explanation:"Malign means speak evil of."},
    {number:65,word:"METICULOUS",options:{A:"Careless",B:"Precise",C:"Weak",D:"Lazy"},answer:"B",explanation:"Meticulous means very careful."},
    {number:66,word:"MODEST",options:{A:"Arrogant",B:"Humble",C:"Proud",D:"Loud"},answer:"B",explanation:"Modest means humble."},
    {number:67,word:"MONOTONOUS",options:{A:"Exciting",B:"Boring",C:"Colorful",D:"Pleasant"},answer:"B",explanation:"Monotonous means repetitive and dull."},
    {number:68,word:"NONCHALANT",options:{A:"Concerned",B:"Unconcerned",C:"Nervous",D:"Excited"},answer:"B",explanation:"Nonchalant means casually calm."},
    {number:69,word:"OPAQUE",options:{A:"Transparent",B:"Unclear",C:"Bright",D:"Thin"},answer:"B",explanation:"Opaque means difficult to understand."},
    {number:70,word:"ORTHODOX",options:{A:"Unconventional",B:"Traditional",C:"Modern",D:"Strange"},answer:"B",explanation:"Orthodox means conventional."},
    {number:71,word:"PENSIVE",options:{A:"Thoughtful",B:"Careless",C:"Happy",D:"Angry"},answer:"A",explanation:"Pensive means deeply thoughtful."},
    {number:72,word:"PERSISTENT",options:{A:"Weak",B:"Determined",C:"Lazy",D:"Careless"},answer:"B",explanation:"Persistent means continuing firmly."},
    {number:73,word:"PERTINENT",options:{A:"Irrelevant",B:"Relevant",C:"Weak",D:"Confusing"},answer:"B",explanation:"Pertinent means related to the matter."},
    {number:74,word:"PIOUS",options:{A:"Religious",B:"Wicked",C:"Cruel",D:"Harsh"},answer:"A",explanation:"Pious means devoutly religious."},
    {number:75,word:"PREVALENT",options:{A:"Rare",B:"Common",C:"Hidden",D:"Unusual"},answer:"B",explanation:"Prevalent means widespread."},
    {number:76,word:"PROFUSE",options:{A:"Scarce",B:"Abundant",C:"Tiny",D:"Weak"},answer:"B",explanation:"Profuse means plentiful."},
    {number:77,word:"PROHIBIT",options:{A:"Allow",B:"Forbid",C:"Encourage",D:"Support"},answer:"B",explanation:"Prohibit means prevent by law."},
    {number:78,word:"RELUCTANT",options:{A:"Eager",B:"Unwilling",C:"Happy",D:"Excited"},answer:"B",explanation:"Reluctant means hesitant."},
    {number:79,word:"RENOUNCE",options:{A:"Accept",B:"Reject",C:"Approve",D:"Encourage"},answer:"B",explanation:"Renounce means give up formally."},
    {number:80,word:"REPROACH",options:{A:"Praise",B:"Blame",C:"Respect",D:"Support"},answer:"B",explanation:"Reproach means express disappointment."},
    {number:81,word:"RESOLVE",options:{A:"Confusion",B:"Determination",C:"Weakness",D:"Fear"},answer:"B",explanation:"Resolve means firm determination."},
    {number:82,word:"RESTRAIN",options:{A:"Encourage",B:"Control",C:"Support",D:"Expand"},answer:"B",explanation:"Restrain means hold back."},
    {number:83,word:"RETRIEVE",options:{A:"Lose",B:"Recover",C:"Reject",D:"Destroy"},answer:"B",explanation:"Retrieve means get back."},
    {number:84,word:"RIGID",options:{A:"Flexible",B:"Stiff",C:"Soft",D:"Gentle"},answer:"B",explanation:"Rigid means inflexible."},
    {number:85,word:"SCARCE",options:{A:"Plenty",B:"Rare",C:"Common",D:"Excessive"},answer:"B",explanation:"Scarce means insufficient."},
    {number:86,word:"SHREWD",options:{A:"Foolish",B:"Clever",C:"Weak",D:"Lazy"},answer:"B",explanation:"Shrewd means sharp-minded."},
    {number:87,word:"SINCERE",options:{A:"Honest",B:"Fake",C:"Dishonest",D:"Harsh"},answer:"A",explanation:"Sincere means genuine."},
    {number:88,word:"SKEPTICAL",options:{A:"Trusting",B:"Doubtful",C:"Certain",D:"Honest"},answer:"B",explanation:"Skeptical means doubtful."},
    {number:89,word:"SLANDER",options:{A:"Praise",B:"Defamation",C:"Respect",D:"Honor"},answer:"B",explanation:"Slander means false spoken statements."},
    {number:90,word:"SOLEMN",options:{A:"Cheerful",B:"Serious",C:"Funny",D:"Excited"},answer:"B",explanation:"Solemn means grave and serious."},
    {number:91,word:"SPARSE",options:{A:"Dense",B:"Scanty",C:"Thick",D:"Abundant"},answer:"B",explanation:"Sparse means thinly scattered."},
    {number:92,word:"SPONTANEOUS",options:{A:"Planned",B:"Natural",C:"Forced",D:"Delayed"},answer:"B",explanation:"Spontaneous means unplanned."},
    {number:93,word:"STURDY",options:{A:"Weak",B:"Strong",C:"Fragile",D:"Delicate"},answer:"B",explanation:"Sturdy means strongly built."},
    {number:94,word:"SUBTLE",options:{A:"Obvious",B:"Delicate",C:"Loud",D:"Clear"},answer:"B",explanation:"Subtle means not obvious."},
    {number:95,word:"SUPPRESS",options:{A:"Encourage",B:"Restrain",C:"Expand",D:"Allow"},answer:"B",explanation:"Suppress means stop by force."},
    {number:96,word:"SWIFT",options:{A:"Slow",B:"Fast",C:"Weak",D:"Calm"},answer:"B",explanation:"Swift means quick."},
    {number:97,word:"THRIFTY",options:{A:"Wasteful",B:"Economical",C:"Rich",D:"Generous"},answer:"B",explanation:"Thrifty means careful with money."},
    {number:98,word:"TRANQUIL",options:{A:"Noisy",B:"Peaceful",C:"Angry",D:"Rough"},answer:"B",explanation:"Tranquil means calm and quiet."},
    {number:99,word:"VAGUE",options:{A:"Clear",B:"Uncertain",C:"Exact",D:"Definite"},answer:"B",explanation:"Vague means not clear."},
    {number:100,word:"WITTY",options:{A:"Dull",B:"Cleverly humorous",C:"Serious",D:"Weak"},answer:"B",explanation:"Witty means cleverly funny."}
  ]},
  { part: "B", questions: [
    {number:1,word:"ABERRATION",options:{A:"Normality",B:"Deviation",C:"Perfection",D:"Balance"},answer:"B",explanation:"Aberration means something different from the norm."},
    {number:2,word:"ACUMEN",options:{A:"Ignorance",B:"Sharpness",C:"Laziness",D:"Weakness"},answer:"B",explanation:"Acumen means keen insight or judgment."},
    {number:3,word:"ALACRITY",options:{A:"Slowness",B:"Eagerness",C:"Fear",D:"Sadness"},answer:"B",explanation:"Alacrity means cheerful readiness."},
    {number:4,word:"AMELIORATE",options:{A:"Worsen",B:"Improve",C:"Delay",D:"Destroy"},answer:"B",explanation:"Ameliorate means to make better."},
    {number:5,word:"ANACHRONISTIC",options:{A:"Modern",B:"Outdated",C:"Advanced",D:"Current"},answer:"B",explanation:"Anachronistic means belonging to an earlier time."},
    {number:6,word:"APATHETIC",options:{A:"Interested",B:"Indifferent",C:"Excited",D:"Passionate"},answer:"B",explanation:"Apathetic means lacking interest or emotion."},
    {number:7,word:"AUSTERE",options:{A:"Luxurious",B:"Severe",C:"Cheerful",D:"Soft"},answer:"B",explanation:"Austere means strict and simple."},
    {number:8,word:"BELLIGERENT",options:{A:"Peaceful",B:"Aggressive",C:"Calm",D:"Friendly"},answer:"B",explanation:"Belligerent means hostile and combative."},
    {number:9,word:"CACOPHONY",options:{A:"Harmony",B:"Harsh noise",C:"Silence",D:"Music"},answer:"B",explanation:"Cacophony means unpleasant sound."},
    {number:10,word:"CAPRICIOUS",options:{A:"Predictable",B:"Unpredictable",C:"Honest",D:"Stable"},answer:"B",explanation:"Capricious means impulsive and changeable."},
    {number:11,word:"CAUSTIC",options:{A:"Gentle",B:"Sarcastic",C:"Sweet",D:"Humble"},answer:"B",explanation:"Caustic means sharply critical."},
    {number:12,word:"COGENT",options:{A:"Weak",B:"Convincing",C:"Confusing",D:"Doubtful"},answer:"B",explanation:"Cogent means clear and persuasive."},
    {number:13,word:"CONVOLUTED",options:{A:"Simple",B:"Complicated",C:"Short",D:"Direct"},answer:"B",explanation:"Convoluted means extremely complex."},
    {number:14,word:"DEARTH",options:{A:"Abundance",B:"Shortage",C:"Comfort",D:"Wealth"},answer:"B",explanation:"Dearth means scarcity."},
    {number:15,word:"DEMURE",options:{A:"Bold",B:"Modest",C:"Loud",D:"Violent"},answer:"B",explanation:"Demure means shy and modest."},
    {number:16,word:"DERIDE",options:{A:"Praise",B:"Mock",C:"Respect",D:"Support"},answer:"B",explanation:"Deride means to ridicule."},
    {number:17,word:"DESPOTIC",options:{A:"Democratic",B:"Tyrannical",C:"Fair",D:"Honest"},answer:"B",explanation:"Despotic means exercising absolute power cruelly."},
    {number:18,word:"DIATRIBE",options:{A:"Compliment",B:"Bitter criticism",C:"Discussion",D:"Joke"},answer:"B",explanation:"Diatribe means a forceful verbal attack."},
    {number:19,word:"DILATORY",options:{A:"Prompt",B:"Delaying",C:"Fast",D:"Active"},answer:"B",explanation:"Dilatory means intended to delay."},
    {number:20,word:"DISPARAGE",options:{A:"Praise",B:"Belittle",C:"Encourage",D:"Respect"},answer:"B",explanation:"Disparage means to speak negatively about."},
    {number:21,word:"ECLECTIC",options:{A:"Limited",B:"Diverse",C:"Uniform",D:"Narrow"},answer:"B",explanation:"Eclectic means selecting from many sources."},
    {number:22,word:"EGREGIOUS",options:{A:"Outstandingly bad",B:"Excellent",C:"Small",D:"Minor"},answer:"A",explanation:"Egregious means remarkably bad."},
    {number:23,word:"ELOQUENT",options:{A:"Fluent",B:"Silent",C:"Weak",D:"Awkward"},answer:"A",explanation:"Eloquent means persuasive in speaking."},
    {number:24,word:"EPHEMERAL",options:{A:"Permanent",B:"Short-lived",C:"Lasting",D:"Stable"},answer:"B",explanation:"Ephemeral means temporary."},
    {number:25,word:"EQUIVOCATE",options:{A:"Clarify",B:"Be ambiguous",C:"Decide",D:"Explain"},answer:"B",explanation:"Equivocate means to avoid clear statements."},
    {number:26,word:"ERUDITE",options:{A:"Ignorant",B:"Scholarly",C:"Foolish",D:"Simple"},answer:"B",explanation:"Erudite means highly educated."},
    {number:27,word:"EXACERBATE",options:{A:"Improve",B:"Worsen",C:"Calm",D:"Heal"},answer:"B",explanation:"Exacerbate means to make worse."},
    {number:28,word:"FASTIDIOUS",options:{A:"Careless",B:"Meticulous",C:"Lazy",D:"Weak"},answer:"B",explanation:"Fastidious means very attentive to detail."},
    {number:29,word:"FECUND",options:{A:"Barren",B:"Productive",C:"Empty",D:"Weak"},answer:"B",explanation:"Fecund means fertile or productive."},
    {number:30,word:"FLAGRANT",options:{A:"Hidden",B:"Obvious",C:"Secret",D:"Minor"},answer:"B",explanation:"Flagrant means glaringly obvious."},
    {number:31,word:"GARRULOUS",options:{A:"Silent",B:"Talkative",C:"Shy",D:"Quiet"},answer:"B",explanation:"Garrulous means excessively talkative."},
    {number:32,word:"HACKNEYED",options:{A:"Original",B:"Overused",C:"Fresh",D:"Rare"},answer:"B",explanation:"Hackneyed means lacking originality."},
    {number:33,word:"ICONOCLAST",options:{A:"Traditionalist",B:"Rebel",C:"Follower",D:"Teacher"},answer:"B",explanation:"Iconoclast means one who challenges beliefs."},
    {number:34,word:"IMPECUNIOUS",options:{A:"Wealthy",B:"Poor",C:"Generous",D:"Rich"},answer:"B",explanation:"Impecunious means lacking money."},
    {number:35,word:"IMPLACABLE",options:{A:"Calm",B:"Relentless",C:"Gentle",D:"Friendly"},answer:"B",explanation:"Implacable means impossible to calm down."},
    {number:36,word:"INTRANSIGENT",options:{A:"Flexible",B:"Stubborn",C:"Kind",D:"Helpful"},answer:"B",explanation:"Intransigent means unwilling to compromise."},
    {number:37,word:"LACONIC",options:{A:"Wordy",B:"Brief",C:"Loud",D:"Emotional"},answer:"B",explanation:"Laconic means using few words."},
    {number:38,word:"LETHARGIC",options:{A:"Energetic",B:"Sluggish",C:"Active",D:"Fast"},answer:"B",explanation:"Lethargic means lacking energy."},
    {number:39,word:"LOQUACIOUS",options:{A:"Silent",B:"Talkative",C:"Calm",D:"Weak"},answer:"B",explanation:"Loquacious means very talkative."},
    {number:40,word:"MENDACIOUS",options:{A:"Truthful",B:"Dishonest",C:"Honest",D:"Noble"},answer:"B",explanation:"Mendacious means lying or untruthful."},
    {number:41,word:"MERCURIAL",options:{A:"Stable",B:"Changeable",C:"Calm",D:"Serious"},answer:"B",explanation:"Mercurial means changing moods quickly."},
    {number:42,word:"MITIGATE",options:{A:"Worsen",B:"Reduce",C:"Expand",D:"Delay"},answer:"B",explanation:"Mitigate means make less severe."},
    {number:43,word:"MOROSE",options:{A:"Cheerful",B:"Gloomy",C:"Excited",D:"Energetic"},answer:"B",explanation:"Morose means sullen and gloomy."},
    {number:44,word:"MUNIFICENT",options:{A:"Stingy",B:"Generous",C:"Poor",D:"Weak"},answer:"B",explanation:"Munificent means very generous."},
    {number:45,word:"NEFARIOUS",options:{A:"Wicked",B:"Honest",C:"Noble",D:"Gentle"},answer:"A",explanation:"Nefarious means evil or criminal."},
    {number:46,word:"OBDURATE",options:{A:"Flexible",B:"Stubborn",C:"Weak",D:"Helpful"},answer:"B",explanation:"Obdurate means refusing to change."},
    {number:47,word:"OBSEQUIOUS",options:{A:"Independent",B:"Servile",C:"Proud",D:"Bold"},answer:"B",explanation:"Obsequious means overly submissive."},
    {number:48,word:"OSTENTATIOUS",options:{A:"Modest",B:"Showy",C:"Quiet",D:"Plain"},answer:"B",explanation:"Ostentatious means intended to impress."},
    {number:49,word:"PARSIMONIOUS",options:{A:"Generous",B:"Stingy",C:"Friendly",D:"Wealthy"},answer:"B",explanation:"Parsimonious means extremely frugal."},
    {number:50,word:"PEDANTIC",options:{A:"Informal",B:"Overly academic",C:"Casual",D:"Relaxed"},answer:"B",explanation:"Pedantic means excessively concerned with details."},
    {number:51,word:"PERFUNCTORY",options:{A:"Careful",B:"Superficial",C:"Detailed",D:"Deep"},answer:"B",explanation:"Perfunctory means done with little interest."},
    {number:52,word:"PERNICIOUS",options:{A:"Helpful",B:"Harmful",C:"Useful",D:"Honest"},answer:"B",explanation:"Pernicious means causing great harm."},
    {number:53,word:"PETULANT",options:{A:"Calm",B:"Irritable",C:"Happy",D:"Peaceful"},answer:"B",explanation:"Petulant means easily annoyed."},
    {number:54,word:"PHLEGMATIC",options:{A:"Emotional",B:"Calm",C:"Excited",D:"Nervous"},answer:"B",explanation:"Phlegmatic means unemotional and calm."},
    {number:55,word:"PLACATE",options:{A:"Anger",B:"Soothe",C:"Ignore",D:"Reject"},answer:"B",explanation:"Placate means to calm someone down."},
    {number:56,word:"PRAGMATIC",options:{A:"Idealistic",B:"Practical",C:"Emotional",D:"Unrealistic"},answer:"B",explanation:"Pragmatic means practical and realistic."},
    {number:57,word:"PROLIFIC",options:{A:"Unproductive",B:"Productive",C:"Weak",D:"Empty"},answer:"B",explanation:"Prolific means producing abundantly."},
    {number:58,word:"PROSAIC",options:{A:"Imaginative",B:"Ordinary",C:"Creative",D:"Extraordinary"},answer:"B",explanation:"Prosaic means dull and ordinary."},
    {number:59,word:"PUNGENT",options:{A:"Mild",B:"Sharp",C:"Weak",D:"Sweet"},answer:"B",explanation:"Pungent means having a strong taste or smell."},
    {number:60,word:"QUERULOUS",options:{A:"Cheerful",B:"Complaining",C:"Calm",D:"Friendly"},answer:"B",explanation:"Querulous means complaining frequently."},
    {number:61,word:"RECONDITE",options:{A:"Simple",B:"Obscure",C:"Clear",D:"Common"},answer:"B",explanation:"Recondite means difficult to understand."},
    {number:62,word:"REPUDIATE",options:{A:"Accept",B:"Reject",C:"Support",D:"Approve"},answer:"B",explanation:"Repudiate means to refuse or deny something."},
    {number:63,word:"RETICENT",options:{A:"Talkative",B:"Reserved",C:"Loud",D:"Friendly"},answer:"B",explanation:"Reticent means quiet and unwilling to speak much."},
    {number:64,word:"SANGUINE",options:{A:"Pessimistic",B:"Optimistic",C:"Angry",D:"Nervous"},answer:"B",explanation:"Sanguine means hopeful and confident."},
    {number:65,word:"SCRUPULOUS",options:{A:"Careless",B:"Careful",C:"Lazy",D:"Weak"},answer:"B",explanation:"Scrupulous means very attentive to moral correctness."},
    {number:66,word:"SPORADIC",options:{A:"Continuous",B:"Occasional",C:"Constant",D:"Regular"},answer:"B",explanation:"Sporadic means happening irregularly."},
    {number:67,word:"SPURIOUS",options:{A:"Genuine",B:"False",C:"Honest",D:"Real"},answer:"B",explanation:"Spurious means fake or not genuine."},
    {number:68,word:"STAID",options:{A:"Wild",B:"Serious",C:"Careless",D:"Loud"},answer:"B",explanation:"Staid means calm and respectable."},
    {number:69,word:"SUPERFLUOUS",options:{A:"Necessary",B:"Excessive",C:"Important",D:"Essential"},answer:"B",explanation:"Superfluous means more than needed."},
    {number:70,word:"TACITURN",options:{A:"Talkative",B:"Silent",C:"Friendly",D:"Cheerful"},answer:"B",explanation:"Taciturn means speaking very little."},
    {number:71,word:"TEMERITY",options:{A:"Fear",B:"Reckless boldness",C:"Wisdom",D:"Weakness"},answer:"B",explanation:"Temerity means excessive confidence or boldness."},
    {number:72,word:"TENUOUS",options:{A:"Strong",B:"Weak",C:"Solid",D:"Firm"},answer:"B",explanation:"Tenuous means very weak or slight."},
    {number:73,word:"TORPID",options:{A:"Active",B:"Sluggish",C:"Fast",D:"Excited"},answer:"B",explanation:"Torpid means inactive or lazy."},
    {number:74,word:"TRUCULENT",options:{A:"Gentle",B:"Aggressive",C:"Friendly",D:"Calm"},answer:"B",explanation:"Truculent means eager to fight."},
    {number:75,word:"VACILLATE",options:{A:"Decide firmly",B:"Waver",C:"Agree",D:"Support"},answer:"B",explanation:"Vacillate means to be indecisive."},
    {number:76,word:"VENERABLE",options:{A:"Disrespected",B:"Honored",C:"Young",D:"Weak"},answer:"B",explanation:"Venerable means deserving respect."},
    {number:77,word:"VERBOSE",options:{A:"Concise",B:"Wordy",C:"Silent",D:"Clear"},answer:"B",explanation:"Verbose means using too many words."},
    {number:78,word:"VICARIOUS",options:{A:"Direct",B:"Indirect",C:"Personal",D:"Real"},answer:"B",explanation:"Vicarious means experienced through another person."},
    {number:79,word:"VINDICATE",options:{A:"Blame",B:"Justify",C:"Punish",D:"Reject"},answer:"B",explanation:"Vindicate means to clear from blame."},
    {number:80,word:"VIRULENT",options:{A:"Harmless",B:"Poisonous",C:"Gentle",D:"Mild"},answer:"B",explanation:"Virulent means extremely harmful."},
    {number:81,word:"VOLATILE",options:{A:"Stable",B:"Unpredictable",C:"Calm",D:"Quiet"},answer:"B",explanation:"Volatile means changing rapidly."},
    {number:82,word:"WARY",options:{A:"Careless",B:"Cautious",C:"Reckless",D:"Friendly"},answer:"B",explanation:"Wary means alert and careful."},
    {number:83,word:"ZEALOUS",options:{A:"Indifferent",B:"Passionate",C:"Lazy",D:"Weak"},answer:"B",explanation:"Zealous means enthusiastic and devoted."},
    {number:84,word:"ABSOLVE",options:{A:"Accuse",B:"Forgive",C:"Punish",D:"Reject"},answer:"B",explanation:"Absolve means to free from guilt."},
    {number:85,word:"ACRIMONIOUS",options:{A:"Friendly",B:"Bitter",C:"Sweet",D:"Gentle"},answer:"B",explanation:"Acrimonious means angry and harsh."},
    {number:86,word:"ADULTERATE",options:{A:"Purify",B:"Corrupt",C:"Improve",D:"Clarify"},answer:"B",explanation:"Adulterate means to make impure."},
    {number:87,word:"ANTAGONIZE",options:{A:"Please",B:"Provoke",C:"Comfort",D:"Encourage"},answer:"B",explanation:"Antagonize means to cause hostility."},
    {number:88,word:"APPEASE",options:{A:"Aggravate",B:"Satisfy",C:"Ignore",D:"Reject"},answer:"B",explanation:"Appease means to calm or satisfy."},
    {number:89,word:"BUCOLIC",options:{A:"Urban",B:"Rural",C:"Modern",D:"Industrial"},answer:"B",explanation:"Bucolic means related to countryside life."},
    {number:90,word:"CANDOR",options:{A:"Dishonesty",B:"Honesty",C:"Fear",D:"Weakness"},answer:"B",explanation:"Candor means openness and honesty."},
    {number:91,word:"CHICANERY",options:{A:"Honesty",B:"Trickery",C:"Wisdom",D:"Courage"},answer:"B",explanation:"Chicanery means deception by trickery."},
    {number:92,word:"CLEMENCY",options:{A:"Cruelty",B:"Mercy",C:"Punishment",D:"Harshness"},answer:"B",explanation:"Clemency means mercy or forgiveness."},
    {number:93,word:"COPIOUS",options:{A:"Scarce",B:"Abundant",C:"Tiny",D:"Weak"},answer:"B",explanation:"Copious means plentiful."},
    {number:94,word:"DEFERENCE",options:{A:"Disrespect",B:"Respect",C:"Anger",D:"Hatred"},answer:"B",explanation:"Deference means respectful submission."},
    {number:95,word:"DIDACTIC",options:{A:"Entertaining",B:"Instructive",C:"Confusing",D:"Emotional"},answer:"B",explanation:"Didactic means intended to teach."},
    {number:96,word:"DISSONANCE",options:{A:"Harmony",B:"Conflict",C:"Peace",D:"Agreement"},answer:"B",explanation:"Dissonance means lack of harmony."},
    {number:97,word:"ENERVATE",options:{A:"Strengthen",B:"Weaken",C:"Encourage",D:"Energize"},answer:"B",explanation:"Enervate means to drain energy."},
    {number:98,word:"EULOGY",options:{A:"Criticism",B:"Praise",C:"Complaint",D:"Warning"},answer:"B",explanation:"Eulogy means a speech of praise."},
    {number:99,word:"EXONERATE",options:{A:"Accuse",B:"Free from blame",C:"Punish",D:"Reject"},answer:"B",explanation:"Exonerate means to prove innocent."},
    {number:100,word:"FASTIDIOUS",options:{A:"Careless",B:"Very careful",C:"Lazy",D:"Weak"},answer:"B",explanation:"Fastidious means paying close attention to detail."}
  ]},
  { part: "C", questions: [
    {number:1,word:"CORPULENT",options:{A:"Lean",B:"Gaunt",C:"Emaciated",D:"Obese"},answer:"D",explanation:"Corpulent means excessively fat."},
    {number:2,word:"BRIEF",options:{A:"Limited",B:"Small",C:"Little",D:"Short"},answer:"D",explanation:"Brief means short in duration or length."},
    {number:3,word:"EMBEZZLE",options:{A:"Misappropriate",B:"Balance",C:"Remunerate",D:"Clear"},answer:"A",explanation:"Embezzle means to steal money dishonestly."},
    {number:4,word:"AUGUST",options:{A:"Common",B:"Ridiculous",C:"Dignified",D:"Petty"},answer:"C",explanation:"August means respected and impressive."},
    {number:5,word:"STRINGENT",options:{A:"Flexible",B:"Lenient",C:"Rigorous",D:"Mild"},answer:"C",explanation:"Stringent means strict or severe."},
    {number:6,word:"LAMENT",options:{A:"Celebrate",B:"Complain",C:"Rejoice",D:"Approve"},answer:"B",explanation:"Lament means to express sorrow or regret."},
    {number:7,word:"MAYHEM",options:{A:"Peace",B:"Havoc",C:"Order",D:"Calmness"},answer:"B",explanation:"Mayhem means chaos or violent disorder."},
    {number:8,word:"PONDER",options:{A:"Ignore",B:"Think",C:"Sleep",D:"Reject"},answer:"B",explanation:"Ponder means to think carefully."},
    {number:9,word:"TACITURNITY",options:{A:"Talkativeness",B:"Reserve",C:"Boldness",D:"Anger"},answer:"B",explanation:"Taciturnity means the habit of speaking very little."},
    {number:10,word:"WARY",options:{A:"Careless",B:"Vigilant",C:"Weak",D:"Friendly"},answer:"B",explanation:"Wary means cautious and alert."},
    {number:11,word:"GARRULITY",options:{A:"Silence",B:"Wisdom",C:"Loquaciousness",D:"Anger"},answer:"C",explanation:"Garrulity means excessive talking."},
    {number:12,word:"CANDID",options:{A:"Frank",B:"Secretive",C:"Careful",D:"Hesitant"},answer:"A",explanation:"Candid means honest and straightforward."},
    {number:13,word:"ABATE",options:{A:"Increase",B:"Reduce",C:"Expand",D:"Continue"},answer:"B",explanation:"Abate means to lessen or decrease."},
    {number:14,word:"FAMISHED",options:{A:"Hungry",B:"Satisfied",C:"Weak",D:"Sleepy"},answer:"A",explanation:"Famished means extremely hungry."},
    {number:15,word:"OBSTINATE",options:{A:"Flexible",B:"Stubborn",C:"Gentle",D:"Cheerful"},answer:"B",explanation:"Obstinate means refusing to change one's opinion."},
    {number:16,word:"VENERATE",options:{A:"Despise",B:"Respect",C:"Ignore",D:"Punish"},answer:"B",explanation:"Venerate means to respect deeply."},
    {number:17,word:"MITIGATE",options:{A:"Intensify",B:"Relieve",C:"Delay",D:"Expand"},answer:"B",explanation:"Mitigate means to make less severe."},
    {number:18,word:"PLAUSIBLE",options:{A:"Doubtful",B:"Convincing",C:"False",D:"Unreal"},answer:"B",explanation:"Plausible means believable or reasonable."},
    {number:19,word:"CONCUR",options:{A:"Differ",B:"Agree",C:"Fight",D:"Delay"},answer:"B",explanation:"Concur means to agree."},
    {number:20,word:"ZENITH",options:{A:"Lowest point",B:"Decline",C:"Peak",D:"Failure"},answer:"C",explanation:"Zenith means the highest point."},
    {number:21,word:"BENEVOLENT",options:{A:"Kind",B:"Cruel",C:"Selfish",D:"Proud"},answer:"A",explanation:"Benevolent means kind and helpful."},
    {number:22,word:"AUDACIOUS",options:{A:"Bold",B:"Fearful",C:"Weak",D:"Lazy"},answer:"A",explanation:"Audacious means fearless or daring."},
    {number:23,word:"FRUGAL",options:{A:"Wasteful",B:"Economical",C:"Rich",D:"Generous"},answer:"B",explanation:"Frugal means careful with money."},
    {number:24,word:"TRANSPARENT",options:{A:"Clear",B:"Opaque",C:"Dark",D:"Thick"},answer:"A",explanation:"Transparent means easy to see through."},
    {number:25,word:"MELANCHOLY",options:{A:"Happy",B:"Sadness",C:"Anger",D:"Excitement"},answer:"B",explanation:"Melancholy means deep sadness."},
    {number:26,word:"DILIGENT",options:{A:"Lazy",B:"Hardworking",C:"Careless",D:"Slow"},answer:"B",explanation:"Diligent means showing careful effort."},
    {number:27,word:"FURTIVE",options:{A:"Open",B:"Secretive",C:"Loud",D:"Honest"},answer:"B",explanation:"Furtive means secret or sneaky."},
    {number:28,word:"JUBILANT",options:{A:"Miserable",B:"Joyful",C:"Angry",D:"Nervous"},answer:"B",explanation:"Jubilant means extremely happy."},
    {number:29,word:"PRUDENT",options:{A:"Wise",B:"Foolish",C:"Careless",D:"Rash"},answer:"A",explanation:"Prudent means acting wisely and carefully."},
    {number:30,word:"TENACIOUS",options:{A:"Weak",B:"Persistent",C:"Lazy",D:"Simple"},answer:"B",explanation:"Tenacious means determined and persistent."},
    {number:31,word:"ALLEVIATE",options:{A:"Worsen",B:"Relieve",C:"Ignore",D:"Delay"},answer:"B",explanation:"Alleviate means to reduce pain or difficulty."},
    {number:32,word:"AMBIGUOUS",options:{A:"Clear",B:"Uncertain",C:"Honest",D:"Bright"},answer:"B",explanation:"Ambiguous means unclear or having multiple meanings."},
    {number:33,word:"ANNIHILATE",options:{A:"Create",B:"Destroy",C:"Build",D:"Preserve"},answer:"B",explanation:"Annihilate means to destroy completely."},
    {number:34,word:"ARDENT",options:{A:"Passionate",B:"Cold",C:"Weak",D:"Silent"},answer:"A",explanation:"Ardent means enthusiastic or passionate."},
    {number:35,word:"BARREN",options:{A:"Fertile",B:"Unproductive",C:"Green",D:"Moist"},answer:"B",explanation:"Barren means unable to produce."},
    {number:36,word:"CALAMITY",options:{A:"Fortune",B:"Disaster",C:"Pleasure",D:"Celebration"},answer:"B",explanation:"Calamity means a serious disaster."},
    {number:37,word:"COVET",options:{A:"Despise",B:"Desire",C:"Reject",D:"Hide"},answer:"B",explanation:"Covet means to strongly desire something."},
    {number:38,word:"DEARTH",options:{A:"Plenty",B:"Scarcity",C:"Wealth",D:"Comfort"},answer:"B",explanation:"Dearth means shortage or lack."},
    {number:39,word:"ELOQUENT",options:{A:"Fluent",B:"Dumb",C:"Silent",D:"Harsh"},answer:"A",explanation:"Eloquent means persuasive and fluent in speaking."},
    {number:40,word:"EXALT",options:{A:"Praise",B:"Criticize",C:"Punish",D:"Ignore"},answer:"A",explanation:"Exalt means to praise highly."},
    {number:41,word:"FALLACY",options:{A:"Truth",B:"Mistaken belief",C:"Fact",D:"Law"},answer:"B",explanation:"Fallacy means a false idea or mistaken belief."},
    {number:42,word:"FERVID",options:{A:"Lukewarm",B:"Enthusiastic",C:"Weak",D:"Calm"},answer:"B",explanation:"Fervid means intensely enthusiastic."},
    {number:43,word:"GUILE",options:{A:"Honesty",B:"Deceit",C:"Simplicity",D:"Purity"},answer:"B",explanation:"Guile means clever deception."},
    {number:44,word:"HAMPER",options:{A:"Assist",B:"Hinder",C:"Improve",D:"Encourage"},answer:"B",explanation:"Hamper means to obstruct or delay progress."},
    {number:45,word:"IMMACULATE",options:{A:"Dirty",B:"Spotless",C:"Rough",D:"Weak"},answer:"B",explanation:"Immaculate means perfectly clean."},
    {number:46,word:"JEOPARDY",options:{A:"Safety",B:"Danger",C:"Peace",D:"Relief"},answer:"B",explanation:"Jeopardy means danger or risk."},
    {number:47,word:"KNACK",options:{A:"Inability",B:"Skill",C:"Weakness",D:"Fear"},answer:"B",explanation:"Knack means a special skill or talent."},
    {number:48,word:"LUCID",options:{A:"Confusing",B:"Clear",C:"Dim",D:"Rough"},answer:"B",explanation:"Lucid means easy to understand."},
    {number:49,word:"MAGNANIMOUS",options:{A:"Generous",B:"Mean",C:"Angry",D:"Selfish"},answer:"A",explanation:"Magnanimous means generous and forgiving."},
    {number:50,word:"NOVICE",options:{A:"Expert",B:"Beginner",C:"Teacher",D:"Master"},answer:"B",explanation:"Novice means a beginner."},
    {number:51,word:"OMINOUS",options:{A:"Promising",B:"Threatening",C:"Pleasant",D:"Peaceful"},answer:"B",explanation:"Ominous means suggesting danger or bad events."},
    {number:52,word:"PERILOUS",options:{A:"Safe",B:"Dangerous",C:"Calm",D:"Useful"},answer:"B",explanation:"Perilous means full of danger."},
    {number:53,word:"QUIESCENT",options:{A:"Active",B:"Inactive",C:"Loud",D:"Bright"},answer:"B",explanation:"Quiescent means inactive or still."},
    {number:54,word:"RAVAGE",options:{A:"Protect",B:"Destroy",C:"Repair",D:"Build"},answer:"B",explanation:"Ravage means to destroy severely."},
    {number:55,word:"SCRUTINIZE",options:{A:"Ignore",B:"Examine",C:"Delay",D:"Hide"},answer:"B",explanation:"Scrutinize means to inspect carefully."},
    {number:56,word:"TURMOIL",options:{A:"Peace",B:"Confusion",C:"Silence",D:"Order"},answer:"B",explanation:"Turmoil means disorder or confusion."},
    {number:57,word:"UBIQUITOUS",options:{A:"Rare",B:"Everywhere",C:"Tiny",D:"Limited"},answer:"B",explanation:"Ubiquitous means present everywhere."},
    {number:58,word:"VAIN",options:{A:"Humble",B:"Proud",C:"Honest",D:"Weak"},answer:"B",explanation:"Vain means excessively proud of appearance or abilities."},
    {number:59,word:"WITHER",options:{A:"Flourish",B:"Shrink",C:"Grow",D:"Expand"},answer:"B",explanation:"Wither means to dry up or weaken."},
    {number:60,word:"YIELD",options:{A:"Resist",B:"Produce",C:"Refuse",D:"Fight"},answer:"B",explanation:"Yield means to produce or provide."},
    {number:61,word:"ZEALOUS",options:{A:"Indifferent",B:"Enthusiastic",C:"Lazy",D:"Nervous"},answer:"B",explanation:"Zealous means passionately enthusiastic."},
    {number:62,word:"ABHOR",options:{A:"Love",B:"Hate",C:"Respect",D:"Ignore"},answer:"B",explanation:"Abhor means to hate strongly."},
    {number:63,word:"BENEFACTOR",options:{A:"Enemy",B:"Supporter",C:"Rival",D:"Critic"},answer:"B",explanation:"Benefactor means someone who gives help or support."},
    {number:64,word:"CENSURE",options:{A:"Praise",B:"Criticize",C:"Reward",D:"Help"},answer:"B",explanation:"Censure means strong disapproval."},
    {number:65,word:"DAUNTLESS",options:{A:"Fearless",B:"Weak",C:"Timid",D:"Nervous"},answer:"A",explanation:"Dauntless means brave and fearless."},
    {number:66,word:"ECSTATIC",options:{A:"Miserable",B:"Delighted",C:"Angry",D:"Calm"},answer:"B",explanation:"Ecstatic means extremely happy."},
    {number:67,word:"FABRICATE",options:{A:"Destroy",B:"Invent",C:"Reveal",D:"Forget"},answer:"B",explanation:"Fabricate means to invent or create falsely."},
    {number:68,word:"GRATIFY",options:{A:"Displease",B:"Please",C:"Annoy",D:"Hurt"},answer:"B",explanation:"Gratify means to give pleasure or satisfaction."},
    {number:69,word:"HOSTILE",options:{A:"Friendly",B:"Unfriendly",C:"Calm",D:"Honest"},answer:"B",explanation:"Hostile means unfriendly or aggressive."},
    {number:70,word:"ILLUSORY",options:{A:"Real",B:"Imaginary",C:"Solid",D:"Certain"},answer:"B",explanation:"Illusory means based on illusion; not real."},
    {number:71,word:"JOVIAL",options:{A:"Sad",B:"Cheerful",C:"Angry",D:"Tired"},answer:"B",explanation:"Jovial means happy and friendly."},
    {number:72,word:"KEEN",options:{A:"Dull",B:"Sharp",C:"Lazy",D:"Rough"},answer:"B",explanation:"Keen means sharp or eager."},
    {number:73,word:"LOFTY",options:{A:"Low",B:"Noble",C:"Weak",D:"Tiny"},answer:"B",explanation:"Lofty means noble or elevated."},
    {number:74,word:"MEAGER",options:{A:"Plenty",B:"Insufficient",C:"Large",D:"Rich"},answer:"B",explanation:"Meager means lacking in quantity."},
    {number:75,word:"NIMBLE",options:{A:"Slow",B:"Agile",C:"Weak",D:"Careless"},answer:"B",explanation:"Nimble means quick and light in movement."},
    {number:76,word:"OPAQUE",options:{A:"Transparent",B:"Unclear",C:"Bright",D:"Thin"},answer:"B",explanation:"Opaque means not clear or difficult to understand."},
    {number:77,word:"PLACID",options:{A:"Calm",B:"Violent",C:"Angry",D:"Rough"},answer:"A",explanation:"Placid means peaceful and calm."},
    {number:78,word:"QUELL",options:{A:"Encourage",B:"Suppress",C:"Build",D:"Excite"},answer:"B",explanation:"Quell means to put an end to something."},
    {number:79,word:"ROBUST",options:{A:"Weak",B:"Strong",C:"Thin",D:"Sick"},answer:"B",explanation:"Robust means strong and healthy."},
    {number:80,word:"STAGNANT",options:{A:"Flowing",B:"Motionless",C:"Active",D:"Rapid"},answer:"B",explanation:"Stagnant means not moving or developing."},
    {number:81,word:"TACTFUL",options:{A:"Rude",B:"Diplomatic",C:"Foolish",D:"Harsh"},answer:"B",explanation:"Tactful means careful not to offend others."},
    {number:82,word:"UNRULY",options:{A:"Obedient",B:"Disorderly",C:"Calm",D:"Gentle"},answer:"B",explanation:"Unruly means difficult to control."},
    {number:83,word:"VIGOROUS",options:{A:"Weak",B:"Energetic",C:"Lazy",D:"Silent"},answer:"B",explanation:"Vigorous means full of energy."},
    {number:84,word:"WARILY",options:{A:"Carelessly",B:"Cautiously",C:"Boldly",D:"Quickly"},answer:"B",explanation:"Warily means in a careful manner."},
    {number:85,word:"YEARN",options:{A:"Hate",B:"Desire",C:"Forget",D:"Reject"},answer:"B",explanation:"Yearn means to long strongly for something."},
    {number:86,word:"ZEST",options:{A:"Boredom",B:"Enthusiasm",C:"Fear",D:"Silence"},answer:"B",explanation:"Zest means great excitement and interest."},
    {number:87,word:"ACCLAIM",options:{A:"Criticism",B:"Praise",C:"Punishment",D:"Rejection"},answer:"B",explanation:"Acclaim means enthusiastic approval or praise."},
    {number:88,word:"BRISK",options:{A:"Slow",B:"Quick",C:"Lazy",D:"Weak"},answer:"B",explanation:"Brisk means quick and energetic."},
    {number:89,word:"CRAFTY",options:{A:"Honest",B:"Cunning",C:"Innocent",D:"Gentle"},answer:"B",explanation:"Crafty means clever in a dishonest way."},
    {number:90,word:"DORMANT",options:{A:"Active",B:"Inactive",C:"Bright",D:"Energetic"},answer:"B",explanation:"Dormant means inactive or asleep."},
    {number:91,word:"ELATED",options:{A:"Sad",B:"Overjoyed",C:"Angry",D:"Calm"},answer:"B",explanation:"Elated means extremely happy."},
    {number:92,word:"FEASIBLE",options:{A:"Impossible",B:"Practical",C:"Unreal",D:"Useless"},answer:"B",explanation:"Feasible means possible and practical."},
    {number:93,word:"GRIM",options:{A:"Cheerful",B:"Stern",C:"Soft",D:"Pleasant"},answer:"B",explanation:"Grim means serious and gloomy."},
    {number:94,word:"HASTEN",options:{A:"Delay",B:"Accelerate",C:"Stop",D:"Relax"},answer:"B",explanation:"Hasten means to speed up."},
    {number:95,word:"INFER",options:{A:"Deduce",B:"Confuse",C:"Repeat",D:"Forget"},answer:"A",explanation:"Infer means to conclude from evidence."},
    {number:96,word:"LENIENT",options:{A:"Strict",B:"Merciful",C:"Harsh",D:"Angry"},answer:"B",explanation:"Lenient means tolerant and forgiving."},
    {number:97,word:"MUNDANE",options:{A:"Extraordinary",B:"Ordinary",C:"Exciting",D:"Noble"},answer:"B",explanation:"Mundane means ordinary or common."},
    {number:98,word:"OUST",options:{A:"Retain",B:"Expel",C:"Welcome",D:"Invite"},answer:"B",explanation:"Oust means to force out or remove."},
    {number:99,word:"PRECARIOUS",options:{A:"Safe",B:"Risky",C:"Stable",D:"Certain"},answer:"B",explanation:"Precarious means dangerous or uncertain."},
    {number:100,word:"RESILIENT",options:{A:"Fragile",B:"Flexible",C:"Weak",D:"Stiff"},answer:"B",explanation:"Resilient means able to recover quickly from difficulties."}
  ]}
];

let globalIndex = 0;
export const ALL_WORDS = [];

RAW_PARTS.forEach(part => {
  part.questions.forEach(q => {
    ALL_WORDS.push({
      index: globalIndex++,
      word: q.word,
      meaning: q.options[q.answer],
      explanation: q.explanation,
      options: q.options,
      answer: q.answer,
      part: part.part,
      difficulty: part.part === 'A' ? 'foundation' : part.part === 'B' ? 'advanced' : 'exam-level'
    });
  });
});

export const WORD_COUNT = ALL_WORDS.length;

export const LEVELS = Array.from({ length: TOTAL_LEVELS }, (_, i) => ({
  number: i + 1,
  title: `Level ${i + 1}`,
  wordIndices: Array.from({ length: WORDS_PER_LEVEL }, (_, j) => i * WORDS_PER_LEVEL + j),
  difficulty: i < 5 ? 'foundation' : i < 10 ? 'advanced' : 'exam-level'
}));

export const DIFFICULTY_MAP = {
  'foundation':  { label: 'Foundation',  color: 'text-success',  bg: 'bg-success/10',  border: 'border-success/20' },
  'advanced':    { label: 'Advanced',    color: 'text-primary',  bg: 'bg-primary/10',  border: 'border-primary/20' },
  'exam-level':  { label: 'Exam Level',  color: 'text-accent',   bg: 'bg-accent/10',   border: 'border-accent/20'  }
};

export const CONFUSION_CLUSTERS = [
  ['LACONIC','TACITURN','RETICENT','CONCISE','BREVITY'],
  ['GARRULOUS','LOQUACIOUS','VERBOSE'],
  ['ADAMANT','OBDURATE','INTRANSIGENT','OBSTINATE','RIGID'],
  ['AFFLUENT','MUNIFICENT','PROFUSE','COPIOUS'],
  ['INDIGENT','IMPECUNIOUS','MEAGER','SCARCE','DEARTH','SPARSE'],
  ['CAPRICIOUS','FICKLE','MERCURIAL','VOLATILE','VACILLATE'],
  ['METICULOUS','FASTIDIOUS','SCRUPULOUS','ASSIDUOUS','DILIGENT'],
  ['DISPARAGE','DERIDE','MALIGN','DEFAMATION','SLANDER','CENSURE'],
  ['PLACATE','APPEASE','MITIGATE','ALLEVIATE','AMELIORATE'],
  ['MOROSE','DISMAL','MELANCHOLY','GRIM','SOLEMN'],
  ['BELLIGERENT','TRUCULENT','HOSTILE','CAUSTIC','ACRIMONIOUS'],
  ['EPHEMERAL','SPORADIC'],
  ['PRAGMATIC','JUDICIOUS','PRUDENT','SHREWD'],
  ['EXTOL','EULOGY','ACCLAIM','EXALT'],
  ['ABSOLVE','EXONERATE','VINDICATE','CONDONE','CLEMENCY'],
];

export function getConfusionCluster(word) {
  const upper = word.toUpperCase();
  return CONFUSION_CLUSTERS.find(c => c.includes(upper)) || [];
}

/**
 * Pure SRS next-review calculator (SM-2 variant).
 * Deterministic — no Date.now() coupling, mockable for tests.
 *
 * @param {{ ease_factor?: number, interval?: number, repetitions?: number, next_review?: string, last_review?: string, mastery_level?: string, confidence?: string }} review
 * @param {'instant'|'hesitated'|'forgot'} confidence
 * @returns {{ ease_factor: number, interval: number, repetitions: number, next_review: string, last_review: string, mastery_level: string, confidence: string }}
 */
export function calculateNextReview(review, confidence) {
  const now = new Date();
  let { ease_factor = 2.5, interval = 0, repetitions = 0 } = review;
  const quality = confidence === 'instant' ? 5 : confidence === 'hesitated' ? 3 : 1;

  if (quality >= 3) {
    if (repetitions === 0) interval = 0.25;
    else if (repetitions === 1) interval = quality === 5 ? 24 : 6;
    else interval = interval * ease_factor;
    repetitions += 1;
  } else {
    repetitions = 0;
    interval = quality === 1 ? 0.05 : 0.25;
  }

  ease_factor = Math.max(1.3, ease_factor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02)));
  const nextReview = new Date(now.getTime() + interval * 3600000);

  let mastery_level = 'new';
  if (repetitions >= 5 && interval > 168) mastery_level = 'mastered';
  else if (repetitions >= 2) mastery_level = 'reviewing';
  else if (repetitions >= 1) mastery_level = 'learning';

  return {
    ease_factor,
    interval,
    repetitions,
    next_review: nextReview.toISOString(),
    last_review: now.toISOString(),
    mastery_level,
    confidence,
  };
}