import {
  AlertCircle,
  Trophy,
  ChevronRight,
  Zap,
  ArrowLeft,
  ArrowRight,
  Brain,
  Keyboard,
  RotateCcw,
  Swords,
  Timer,
  Clock,
  AlertTriangle,
  Check,
  Lightbulb,
  Volume2,
  LogIn,
  TrendingUp,
  Target,
  Award,
} from 'lucide-react';

export {
  AlertCircle as PremiumAlertCircleIcon,
  Trophy as PremiumTrophyIcon,
  ChevronRight as PremiumChevronRightIcon,
  Zap as PremiumMatchingIcon,
  ArrowLeft as PremiumArrowLeftIcon,
  ArrowRight as PremiumArrowRightIcon,
  Brain as PremiumBrainIcon,
  Keyboard as PremiumSpellingIcon,
  RotateCcw as PremiumRotateCCWIcon,
  Swords as PremiumBattleIcon,
  Timer as PremiumTimerIcon,
  Clock as PremiumClockIcon,
  AlertTriangle as PremiumAlertIcon,
  Check as PremiumCheckIcon,
  Lightbulb as PremiumLightbulbIcon,
  Volume2 as PremiumVolumeIcon,
  LogIn as PremiumLoginIcon,
  TrendingUp as PremiumTrendingUpIcon,
  Target as PremiumMCQIcon,
  Award as PremiumAwardIcon,
};
